// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4nKqM-74cW26ySJdIZMhhIYLF3dKfDM',
    appId: '1:499319589082:web:40a5f3f9f96d1081b53de3',
    messagingSenderId: '499319589082',
    projectId: 'mnmn-c521d',
    authDomain: 'mnmn-c521d.firebaseapp.com',
    storageBucket: 'mnmn-c521d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBDxMgDMdc5DysKJ3h_ITGlfHKwBgEf6M',
    appId: '1:499319589082:android:edb9f5b3337293b8b53de3',
    messagingSenderId: '499319589082',
    projectId: 'mnmn-c521d',
    storageBucket: 'mnmn-c521d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcZ6mi1a5iPz6I_quXHqFVvgkJ8yB-OCs',
    appId: '1:499319589082:ios:50a6b41bb48f9ffcb53de3',
    messagingSenderId: '499319589082',
    projectId: 'mnmn-c521d',
    storageBucket: 'mnmn-c521d.appspot.com',
    iosClientId: '499319589082-o1drdmpul4qvu71l60ccc5g5lhtp3igc.apps.googleusercontent.com',
    iosBundleId: 'message.mnmn.app',
  );
}
