version: '3.2'
services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    logging:
      driver: 'none'
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysqldata:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${FORWARD_NGINX_PORT:-80}:80'
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./public
        target: /var/app/public
      - type: bind
        source: ./storage/app
        target: /var/app/storage/app
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "localhost:80/api/healthcheck"]
      retries: 3
      timeout: 5s
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: .
        target: /var/app
    depends_on:
      - mysql
volumes:
  mysqldata:
    driver: 'local'
  php-fpm-socket:
    driver: 'local'
